"""empty message

Revision ID: 1dcb36a74425
Revises: 12c3d27e5901
Create Date: 2022-08-04 13:38:46.205612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcb36a74425'
down_revision = '12c3d27e5901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
