"""empty message

Revision ID: 238efa759fb6
Revises: 
Create Date: 2022-08-02 22:18:29.299923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238efa759fb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('looking_for_talent', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_description')
    op.drop_column('venue', 'looking_for_talent')
    op.drop_column('venue', 'genres')
    op.drop_column('venue', 'website_link')
    # ### end Alembic commands ###
