"""empty message

Revision ID: b943508d1252
Revises: 1dcb36a74425
Create Date: 2022-08-05 23:22:07.006436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b943508d1252'
down_revision = '1dcb36a74425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.drop_column('Shows', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('Shows', 'start_time')
    # ### end Alembic commands ###
