"""empty message

Revision ID: c04dfd3fe065
Revises: 7d4249d817c3
Create Date: 2022-08-02 22:27:55.384976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c04dfd3fe065'
down_revision = '7d4249d817c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.drop_column('Shows', 'state')
    op.drop_column('Shows', 'end_date')
    op.drop_column('Shows', 'name')
    op.drop_column('Shows', 'begin_date')
    op.drop_column('Shows', 'city')
    op.drop_column('Shows', 'host')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('host', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('Shows', sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('Shows', sa.Column('begin_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('Shows', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('Shows', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('Shows', sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('Shows', 'start_date')
    # ### end Alembic commands ###
